<?php

/**
 * @file
 * Contains wmvideo.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function wmvideo_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        // Main module help for the wmvideo module.
        case 'help.page.wmvideo':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Converting a YouTube or Vimeo URL to an embedded player') . '</p>';
            
            return $output;
        
        default:
    }
}

/**
 * Implements hook_theme().
 */
function wmvideo_theme($existing, $type, $theme, $path)
{
    return array(
        'wmvideo_youtube' => array(
            'variables' => array(
                'vid' => NULL,
                'width' => 640,
                'height' => 360,
                'lang' => 'en',
                'origin' => NULL,
                'autoplay' => FALSE,
            ),
        ),
        'wmvideo_vimeo' => array(
            'variables' => array(
                'vid' => NULL,
                'width' => 640,
                'height' => 360,
                'autoplay' => FALSE,
            ),
        ),
    );
}
