<?php

/**
 * Implements @see hook_help().
 */
function wmvideo_help(string $route_name): ?string
{
    if ($route_name !== 'help.page.wmvideo') {
        return null;
    }

    $output = '';
    $output .= '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('Converting a YouTube or Vimeo URL to an embedded player') . '</p>';

    return $output;
}

/**
 * Implements @see hook_theme().
 */
function wmvideo_theme(): array
{
    return [
        'wmvideo_youtube' => [
            'variables' => [
                'vid' => null,
                'width' => 640,
                'height' => 360,
                'lang' => 'en',
                'origin' => null,
                'autoplay' => false,
                'disablekb' => '1',
                'title' => "",
            ],
        ],
        'wmvideo_vimeo' => [
            'variables' => [
                'vid' => null,
                'width' => 640,
                'height' => 360,
                'autoplay' => false,
                'keyboard' => 'false',
                'title' => "",
            ],
        ],
    ];
}
